import { Template } from './template';

export const reactTailwind: Template = {
  name: 'basic',
  dependencies: ['@heroicons/react', 'react', 'react-dom'],
  packageJson: {
    // name: safeName,
    version: '0.1.0',
    license: 'MIT',
    // author: author,
    main: './dist/index.cjs',
    module: './dist/index.mjs',
    exports: {
      './package.json': './package.json',
      '.': {
        import: './dist/index.mjs',
        require: './dist/index.cjs',
      },
    },
    // module: `dist/${safeName}.mjs`,
    typings: `dist/index.d.ts`,
    files: ['dist', 'src'],
    engines: {
      node: '>=14',
    },
    scripts: {
      start: 'tsx watch src/index.ts',
      build: 'tsup src/index.ts --format=esm',
      test: 'vitest',
      prepare: 'build',
    },
    devDependencies: {
      '@commitlint/cli': '18.5.0',
      '@commitlint/config-conventional': '18.5.0',
      '@tailwindcss/forms': '0.5.7',
      '@testing-library/jest-dom': '^6.3.0',
      '@testing-library/react': '14.1.2',
      '@types/node': '20.11.6',
      '@types/react': '^18.2.48',
      '@types/react-dom': '^18.2.18',
      '@typescript-eslint/eslint-plugin': '^6.19.1',
      '@typescript-eslint/parser': '^6.19.1',
      '@vitejs/plugin-react': '^4.2.1',
      autoprefixer: '10.4.17',
      eslint: '^8.56.0',
      'eslint-plugin-import': '2.29.1',
      'eslint-plugin-react': '7.33.2',
      'eslint-plugin-react-hooks': '^4.6.0',
      'eslint-plugin-react-refresh': '^0.4.5',
      'happy-dom': '^13.3.1',
      husky: '9.0.1',
      'lint-staged': '15.2.0',
      postcss: '8.4.33',
      prettier: '3.2.4',
      tailwindcss: '3.4.1',
      typescript: '^5.3.3',
      vite: '^5.0.12',
      'vite-preset-react': '2.3.0',
      vitest: '^1.2.1',
    },
    peerDependencies: {},
    prettier: {
      printWidth: 80,
      semi: false,
      singleQuote: true,
      trailingComma: 'es5',
    },
  },
};
